#!/usr/bin/env node

import readline from 'readline';
import fs from 'fs/promises';
import path from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query: string): Promise<string> {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function main() {
  console.log('\n🏢 AI Office Platform - Onboarding\n');
  console.log('Добро пожаловать! Давай настроим твой AI офис.\n');

  // Path to .env in project root (aipanel/.env)
  // When running from backend/, go up one level
  const envPath = path.resolve(process.cwd(), '../.env');
  let envExists = false;
  
  try {
    await fs.access(envPath);
    envExists = true;
    console.log('⚠️  .env файл уже существует.');
    const overwrite = await question('Хочешь перенастроить? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n✅ Используем существующую конфигурацию.');
      rl.close();
      return;
    }
  } catch {
    // .env doesn't exist, continue
  }

  console.log('\n📋 Выбери LLM провайдера:\n');
  console.log('1. OpenRouter (рекомендуется - есть бесплатный тариф)');
  console.log('2. OpenAI');
  console.log('3. Ollama (локально, бесплатно)');
  console.log('4. Anthropic (Claude)\n');

  const choice = await question('Твой выбор (1-4): ');

  let envContent = `# AI Office Platform Configuration
# Generated by onboard script

# Server Configuration
NODE_ENV=development
PORT=4000
WS_PORT=4001
FRONTEND_URL=http://localhost:3000

# Agent Configuration
AGENTS_DIR=./agents
SKILLS_DIR=./skills

# Logging
LOG_LEVEL=info

`;

  switch (choice.trim()) {
    case '1': {
      console.log('\n🌐 OpenRouter Setup');
      console.log('Получи бесплатный ключ: https://openrouter.ai/keys\n');
      
      const apiKey = await question('OpenRouter API Key (или Enter для пропуска): ');
      
      if (apiKey.trim()) {
        envContent += `# OpenRouter Configuration
OPENROUTER_API_KEY=${apiKey.trim()}
LLM_PROVIDER=openrouter
LLM_MODEL=openai/gpt-3.5-turbo
`;
      } else {
        envContent += `# OpenRouter Configuration (настрой позже)
# OPENROUTER_API_KEY=your-key-here
# LLM_PROVIDER=openrouter
# LLM_MODEL=openai/gpt-3.5-turbo
`;
      }
      
      console.log('\n💡 Популярные бесплатные модели на OpenRouter:');
      console.log('   - openai/gpt-3.5-turbo (быстрая)');
      console.log('   - meta-llama/llama-3-8b-instruct (бесплатная)');
      console.log('   - google/gemini-flash-1.5 (быстрая и бесплатная)');
      break;
    }

    case '2': {
      console.log('\n🤖 OpenAI Setup');
      console.log('Получи ключ: https://platform.openai.com/api-keys\n');
      
      const apiKey = await question('OpenAI API Key (или Enter для пропуска): ');
      
      if (apiKey.trim()) {
        envContent += `# OpenAI Configuration
OPENAI_API_KEY=${apiKey.trim()}
LLM_PROVIDER=openai
LLM_MODEL=gpt-3.5-turbo
`;
      } else {
        envContent += `# OpenAI Configuration (настрой позже)
# OPENAI_API_KEY=sk-proj-your-key-here
# LLM_PROVIDER=openai
# LLM_MODEL=gpt-3.5-turbo
`;
      }
      break;
    }

    case '3': {
      console.log('\n🦙 Ollama Setup (локально)');
      console.log('\nУстанови Ollama:');
      console.log('  macOS: brew install ollama');
      console.log('  Linux: curl -fsSL https://ollama.ai/install.sh | sh');
      console.log('  Windows: https://ollama.ai/download\n');
      console.log('Затем запусти: ollama serve');
      console.log('И скачай модель: ollama pull llama2\n');
      
      const endpoint = await question('Ollama endpoint (Enter = http://localhost:11434): ');
      const model = await question('Модель (Enter = llama2): ');
      
      envContent += `# Ollama Configuration
OLLAMA_ENDPOINT=${endpoint.trim() || 'http://localhost:11434'}
LLM_PROVIDER=ollama
LLM_MODEL=${model.trim() || 'llama2'}
`;
      break;
    }

    case '4': {
      console.log('\n🧠 Anthropic (Claude) Setup');
      console.log('Получи ключ: https://console.anthropic.com/\n');
      
      const apiKey = await question('Anthropic API Key (или Enter для пропуска): ');
      
      if (apiKey.trim()) {
        envContent += `# Anthropic Configuration
ANTHROPIC_API_KEY=${apiKey.trim()}
LLM_PROVIDER=anthropic
LLM_MODEL=claude-3-haiku-20240307
`;
      } else {
        envContent += `# Anthropic Configuration (настрой позже)
# ANTHROPIC_API_KEY=sk-ant-your-key-here
# LLM_PROVIDER=anthropic
# LLM_MODEL=claude-3-haiku-20240307
`;
      }
      break;
    }

    default:
      console.log('\n❌ Неверный выбор. Используй .env.example для ручной настройки.');
      rl.close();
      return;
  }

  // Optional: Telegram setup
  console.log('\n📱 Telegram Bot (опционально, можно настроить позже)');
  const setupTelegram = await question('Настроить Telegram бота сейчас? (y/n): ');
  
  if (setupTelegram.toLowerCase() === 'y') {
    console.log('\nПолучи токен: https://t.me/BotFather\n');
    const token = await question('Telegram Bot Token (или Enter для пропуска): ');
    
    if (token.trim()) {
      envContent += `
# Telegram Configuration
TELEGRAM_BOT_TOKEN=${token.trim()}
TELEGRAM_ENABLED=true
`;
    }
  } else {
    envContent += `
# Telegram Configuration (настрой позже)
# TELEGRAM_BOT_TOKEN=your-bot-token
# TELEGRAM_ENABLED=false
`;
  }

  // Write .env file
  try {
    await fs.writeFile(envPath, envContent, 'utf-8');
    console.log('\n✅ Конфигурация сохранена в .env');
  } catch (error) {
    console.error('\n❌ Ошибка при сохранении .env:', error);
    rl.close();
    return;
  }

  // Create first agent
  console.log('\n🤖 Создаем твоего первого агента...\n');
  
  const agentName = await question('Имя агента (Enter = MyAssistant): ');
  const agentId = (agentName.trim() || 'MyAssistant').toLowerCase().replace(/\s+/g, '-');
  const displayName = agentName.trim() || 'MyAssistant';

  // Determine provider and model based on choice
  let provider = 'openai';
  let model = 'gpt-3.5-turbo';
  
  if (choice === '1') {
    provider = 'openrouter';
    model = 'openai/gpt-3.5-turbo';
  } else if (choice === '3') {
    provider = 'ollama';
    model = 'llama2';
  } else if (choice === '4') {
    provider = 'anthropic';
    model = 'claude-3-haiku-20240307';
  }

  // Create agent directory
  const agentDir = path.resolve(process.cwd(), `agents/${agentId}`);
  
  try {
    // Check if agents directory exists, if not create it
    const agentsDir = path.resolve(process.cwd(), 'agents');
    try {
      await fs.access(agentsDir);
    } catch {
      await fs.mkdir(agentsDir, { recursive: true });
      console.log('✅ Created agents directory');
    }

    await fs.mkdir(agentDir, { recursive: true });
    await fs.mkdir(path.join(agentDir, 'memory'), { recursive: true });
    await fs.mkdir(path.join(agentDir, 'sessions'), { recursive: true });

    // Create AGENT.md
    const agentMd = `---
id: ${agentId}
name: ${displayName}
type: api-assistant
status: idle
energy: 100
llm:
  provider: ${provider}
  model: ${model}
  temperature: 0.7
  maxTokens: 2000
skills:
  - conversation
  - help
  - analysis
createdAt: ${new Date().toISOString()}
---

# Agent Identity

I am ${displayName}, your AI assistant.

## Personality
- Professional and helpful
- Clear and concise communication
- Proactive problem solver

## Capabilities
- Answer questions and provide information
- Help with tasks and analysis
- Learn from interactions

## Guidelines
- Be helpful and respectful
- Provide accurate information
- Ask for clarification when needed
`;

    await fs.writeFile(path.join(agentDir, 'AGENT.md'), agentMd, 'utf-8');

    // Create MEMORY.md
    const memoryMd = `# Long-term Memory

## Important Information
- Created: ${new Date().toISOString()}
- Purpose: AI assistant for automation and productivity

## Learned Preferences
(Will be updated as we interact)
`;

    await fs.writeFile(path.join(agentDir, 'MEMORY.md'), memoryMd, 'utf-8');

    // Create CONTEXT.md
    const contextMd = `# Current Session Context

Session started: ${new Date().toISOString()}

`;

    await fs.writeFile(path.join(agentDir, 'CONTEXT.md'), contextMd, 'utf-8');

    console.log(`✅ Агент "${displayName}" создан!`);
    console.log(`   ID: ${agentId}`);
    console.log(`   Provider: ${provider}`);
    console.log(`   Model: ${model}`);

  } catch (error) {
    console.error('\n❌ Ошибка при создании агента:', error);
  }

  console.log('\n🎉 Onboarding завершен!\n');
  console.log('Следующие шаги:');
  console.log('1. Запусти backend:');
  console.log('   npm run dev\n');
  console.log('2. В другом терминале запусти frontend:');
  console.log('   cd ../frontend && npm run dev\n');
  console.log('3. Открой браузер: http://localhost:3000\n');

  rl.close();
}

main().catch((error) => {
  console.error('❌ Ошибка:', error);
  rl.close();
  process.exit(1);
});
