#!/usr/bin/env node
import inquirer from 'inquirer';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../utils/logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface OnboardConfig {
  agentName: string;
  llmProvider: 'openai' | 'openrouter' | 'ollama' | 'anthropic';
  llmModel: string;
  apiKey?: string;
  telegramToken?: string;
  enableTelegram: boolean;
}

async function onboard() {
  console.log(`
╔═══════════════════════════════════════╗
║   🤖 AI Agent Platform - Onboarding   ║
╔═══════════════════════════════════════╝
  `);

  try {
    // Step 1: Agent Configuration
    const agentConfig = await inquirer.prompt<OnboardConfig>([
      {
        type: 'input',
        name: 'agentName',
        message: 'What should we call your agent?',
        default: 'MyAgent',
      },
      {
        type: 'list',
        name: 'llmProvider',
        message: 'Which LLM provider do you want to use?',
        choices: [
          { name: 'OpenRouter (recommended, free tier available)', value: 'openrouter' },
          { name: 'OpenAI', value: 'openai' },
          { name: 'Ollama (local)', value: 'ollama' },
          { name: 'Anthropic', value: 'anthropic' },
        ],
      },
    ]);

    // Step 2: Model Selection based on provider
    let modelChoices: string[] = [];
    switch (agentConfig.llmProvider) {
      case 'openrouter':
        modelChoices = [
          'openai/gpt-3.5-turbo',
          'openai/gpt-4',
          'anthropic/claude-3-haiku',
          'anthropic/claude-3-sonnet',
          'anthropic/claude-3-opus',
          'meta-llama/llama-3-8b',
        ];
        break;
      case 'openai':
        modelChoices = ['gpt-3.5-turbo', 'gpt-4', 'gpt-4-turbo'];
        break;
      case 'ollama':
        modelChoices = ['llama2', 'mistral', 'codellama', 'phi'];
        break;
      case 'anthropic':
        modelChoices = ['claude-3-haiku', 'claude-3-sonnet', 'claude-3-opus'];
        break;
    }

    const modelAnswer = await inquirer.prompt([
      {
        type: 'list',
        name: 'llmModel',
        message: 'Which model do you want to use?',
        choices: modelChoices,
      },
    ]);

    agentConfig.llmModel = modelAnswer.llmModel;

    // Step 3: API Key (if not Ollama)
    if (agentConfig.llmProvider !== 'ollama') {
      const apiKeyAnswer = await inquirer.prompt([
        {
          type: 'password',
          name: 'apiKey',
          message: `Enter your ${agentConfig.llmProvider.toUpperCase()} API key:`,
          mask: '*',
        },
      ]);
      agentConfig.apiKey = apiKeyAnswer.apiKey;
    }

    // Step 4: Telegram Configuration
    const telegramAnswer = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'enableTelegram',
        message: 'Do you want to enable Telegram bot?',
        default: false,
      },
    ]);

    agentConfig.enableTelegram = telegramAnswer.enableTelegram;

    if (agentConfig.enableTelegram) {
      const tokenAnswer = await inquirer.prompt([
        {
          type: 'input',
          name: 'telegramToken',
          message: 'Enter your Telegram bot token (from @BotFather):',
        },
      ]);
      agentConfig.telegramToken = tokenAnswer.telegramToken;
    }

    // Step 5: Create .env file
    await createEnvFile(agentConfig);

    // Step 6: Create agent directory and files
    await createAgentFiles(agentConfig);

    console.log(`
✅ Onboarding complete!

Your agent "${agentConfig.agentName}" is ready.

Next steps:
1. Start the gateway:
   npm run gateway

2. Chat with your agent via CLI:
   npm run chat

3. ${agentConfig.enableTelegram ? 'Your Telegram bot is enabled and will start automatically!' : 'Enable Telegram later by editing agents/${agentConfig.agentName.toLowerCase()}/AGENT.md'}

Happy chatting! 🚀
    `);
  } catch (error) {
    logger.error('Onboarding failed:', error);
    console.error('❌ Onboarding failed:', error);
    process.exit(1);
  }
}

async function createEnvFile(config: OnboardConfig): Promise<void> {
  const envPath = path.join(process.cwd(), '.env');
  
  let envContent = `# AI Agent Platform Configuration
# Generated by onboard script

# LLM Provider
`;

  if (config.llmProvider === 'openrouter' && config.apiKey) {
    envContent += `OPENROUTER_API_KEY=${config.apiKey}\n`;
  } else if (config.llmProvider === 'openai' && config.apiKey) {
    envContent += `OPENAI_API_KEY=${config.apiKey}\n`;
  } else if (config.llmProvider === 'anthropic' && config.apiKey) {
    envContent += `ANTHROPIC_API_KEY=${config.apiKey}\n`;
  }

  if (config.enableTelegram && config.telegramToken) {
    envContent += `\n# Telegram Bot\nTELEGRAM_BOT_TOKEN=${config.telegramToken}\n`;
  }

  envContent += `\n# Server Configuration
PORT=4001
FRONTEND_URL=http://localhost:3000

# Agent Directory
AGENTS_DIR=./agents
`;

  await fs.writeFile(envPath, envContent, 'utf-8');
  logger.info('Created .env file');
}

async function createAgentFiles(config: OnboardConfig): Promise<void> {
  const agentId = config.agentName.toLowerCase().replace(/\s+/g, '');
  const agentDir = path.join(process.cwd(), 'agents', agentId);

  // Create directories
  await fs.mkdir(agentDir, { recursive: true });
  await fs.mkdir(path.join(agentDir, 'memory'), { recursive: true });
  await fs.mkdir(path.join(agentDir, 'sessions'), { recursive: true });

  // Create AGENT.md
  const agentMd = `---
id: ${agentId}
name: ${config.agentName}
type: api-assistant
status: idle
energy: 100
version: 1.0.0
created: ${new Date().toISOString()}
updated: ${new Date().toISOString()}
llm:
  provider: ${config.llmProvider}
  model: ${config.llmModel}
  temperature: 0.7
  maxTokens: 2000
skills:
  - conversation
  - help
  - analysis
  tools:
  enabled:
    - read_file
    - list_directory
    - write_file
    - web_search
    - shell_exec
    - search_web
    - remember_fact
    - update_skills
    - search_files
    - scrape_website
  disabled: []

memory:
  enabled: true
  vectorSearch: false
  maxContextSize: 50000
  rotationThreshold: 45000
${config.enableTelegram && config.telegramToken ? `telegram:
  token: '${config.telegramToken}'
  enabled: true` : ''}
capabilities:
  - text_generation
  - code_generation
  - web_browsing
  - file_operations
permissions:
  canModifyConfig: true
  canModifyMemory: true
  canExecuteCommands: true
  canAccessNetwork: true
  canModifyFiles: true
---

# Agent Configuration

See SOUL.md for personality and TOOLS.md for available tools.
`;

  await fs.writeFile(path.join(agentDir, 'AGENT.md'), agentMd, 'utf-8');

  // Create SOUL.md
  const soulMd = `# Agent Soul - ${config.agentName}

## Core Identity

I am ${config.agentName}, your AI assistant focused on helping you with tasks and providing information.

## Personality Traits

- **Professional**: Clear and concise communication
- **Helpful**: Always try to find solutions
- **Curious**: Ask clarifying questions when needed
- **Honest**: Admit when I don't know something
- **Proactive**: Suggest improvements and alternatives

## Communication Style

- Use appropriate technical language
- Provide examples when helpful
- Break down complex topics
- Ask for feedback and clarification

## Values

- **Transparency**: Explain my reasoning
- **Privacy**: Respect user data
- **Quality**: Provide accurate information
- **Learning**: Improve from interactions

## Boundaries

- I ask for confirmation before executing potentially dangerous operations
- I respect user preferences and working style
- I admit limitations and uncertainties
`;

  await fs.writeFile(path.join(agentDir, 'SOUL.md'), soulMd, 'utf-8');

  // Create MEMORY.md
  await fs.writeFile(
    path.join(agentDir, 'MEMORY.md'),
    '# Long-term Memory\n\n',
    'utf-8'
  );

  // Create CONTEXT.md
  await fs.writeFile(
    path.join(agentDir, 'CONTEXT.md'),
    '# Current Session Context\n\n',
    'utf-8'
  );

  logger.info(`Created agent files in ${agentDir}`);
}

// Run onboard if called directly
if (import.meta.url === `file://${fileURLToPath(process.argv[1])}`) {
  onboard();
}

export { onboard };
