#!/usr/bin/env node
import inquirer from 'inquirer';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../utils/logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface OnboardConfig {
  agentName: string;
  llmProvider: 'openai' | 'openrouter' | 'ollama' | 'anthropic';
  llmModel: string;
  apiKey?: string;
  telegramToken?: string;
  enableTelegram: boolean;
}

async function onboard() {
  console.log(`
╔═══════════════════════════════════════╗
║   🤖 AI Agent Platform - Onboarding   ║
╔═══════════════════════════════════════╝
  `);

  try {
    // Step 1: Agent Configuration
    const agentConfig = await inquirer.prompt<OnboardConfig>([
      {
        type: 'input',
        name: 'agentName',
        message: 'What should we call your agent?',
        default: 'MyAgent',
      },
      {
        type: 'list',
        name: 'llmProvider',
        message: 'Which LLM provider do you want to use?',
        choices: [
          { name: 'OpenRouter (recommended, free tier available)', value: 'openrouter' },
          { name: 'OpenAI', value: 'openai' },
          { name: 'Ollama (local)', value: 'ollama' },
          { name: 'Anthropic', value: 'anthropic' },
        ],
      },
    ]);

    // Step 2: Model Selection based on provider
    let modelChoices: string[] = [];
    switch (agentConfig.llmProvider) {
      case 'openrouter':
        modelChoices = [
          'openai/gpt-3.5-turbo',
          'openai/gpt-4',
          'anthropic/claude-3-haiku',
          'anthropic/claude-3-sonnet',
          'anthropic/claude-3-opus',
          'meta-llama/llama-3-8b',
        ];
        break;
      case 'openai':
        modelChoices = ['gpt-3.5-turbo', 'gpt-4', 'gpt-4-turbo'];
        break;
      case 'ollama':
        modelChoices = ['llama2', 'mistral', 'codellama', 'phi'];
        break;
      case 'anthropic':
        modelChoices = ['claude-3-haiku', 'claude-3-sonnet', 'claude-3-opus'];
        break;
    }

    const modelAnswer = await inquirer.prompt([
      {
        type: 'list',
        name: 'llmModel',
        message: 'Which model do you want to use?',
        choices: modelChoices,
      },
    ]);

    agentConfig.llmModel = modelAnswer.llmModel;

    // Step 3: API Key (if not Ollama)
    if (agentConfig.llmProvider !== 'ollama') {
      const apiKeyAnswer = await inquirer.prompt([
        {
          type: 'password',
          name: 'apiKey',
          message: `Enter your ${agentConfig.llmProvider.toUpperCase()} API key:`,
          mask: '*',
        },
      ]);
      agentConfig.apiKey = apiKeyAnswer.apiKey;
    }

    // Step 4: Telegram Configuration
    const telegramAnswer = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'enableTelegram',
        message: 'Do you want to enable Telegram bot?',
        default: false,
      },
    ]);

    agentConfig.enableTelegram = telegramAnswer.enableTelegram;

    if (agentConfig.enableTelegram) {
      const tokenAnswer = await inquirer.prompt([
        {
          type: 'input',
          name: 'telegramToken',
          message: 'Enter your Telegram bot token (from @BotFather):',
        },
      ]);
      agentConfig.telegramToken = tokenAnswer.telegramToken;
    }

    // Step 5: Create .env file
    await createEnvFile(agentConfig);

    // Step 6: Create agent directory and files
    await createAgentFiles(agentConfig);

    console.log(`
✅ Onboarding complete!

Your agent "${agentConfig.agentName}" is ready.

Next steps:
1. Start the gateway:
   npm run gateway

2. Chat with your agent via CLI:
   npm run chat

3. ${agentConfig.enableTelegram ? 'Your Telegram bot is enabled and will start automatically!' : 'Enable Telegram later by editing agents/${agentConfig.agentName.toLowerCase()}/AGENT.md'}

Happy chatting! 🚀
    `);
  } catch (error) {
    logger.error('Onboarding failed:', error);
    console.error('❌ Onboarding failed:', error);
    process.exit(1);
  }
}

async function createEnvFile(config: OnboardConfig): Promise<void> {
  const envPath = path.join(process.cwd(), '.env');
  
  let envContent = `# AI Agent Platform Configuration
# Generated by onboard script

# LLM Provider
`;

  if (config.llmProvider === 'openrouter' && config.apiKey) {
    envContent += `OPENROUTER_API_KEY=${config.apiKey}\n`;
  } else if (config.llmProvider === 'openai' && config.apiKey) {
    envContent += `OPENAI_API_KEY=${config.apiKey}\n`;
  } else if (config.llmProvider === 'anthropic' && config.apiKey) {
    envContent += `ANTHROPIC_API_KEY=${config.apiKey}\n`;
  }

  if (config.enableTelegram && config.telegramToken) {
    envContent += `\n# Telegram Bot\nTELEGRAM_BOT_TOKEN=${config.telegramToken}\n`;
  }

  envContent += `\n# Server Configuration
PORT=4001
FRONTEND_URL=http://localhost:3000

# Agent Directory
AGENTS_DIR=./agents
`;

  await fs.writeFile(envPath, envContent, 'utf-8');
  logger.info('Created .env file');
}

async function createAgentFiles(config: OnboardConfig): Promise<void> {
  const agentId = config.agentName.toLowerCase().replace(/\s+/g, '');
  const agentDir = path.join(process.cwd(), 'agents', agentId);

  // Create directories
  await fs.mkdir(agentDir, { recursive: true });
  await fs.mkdir(path.join(agentDir, 'memory'), { recursive: true });
  await fs.mkdir(path.join(agentDir, 'sessions'), { recursive: true });

  // Create AGENT.md
  const agentMd = `---
id: ${agentId}
name: ${config.agentName}
type: api-assistant
status: idle
energy: 100
version: 1.0.0
created: ${new Date().toISOString()}
updated: ${new Date().toISOString()}
llm:
  provider: ${config.llmProvider}
  model: ${config.llmModel}
  temperature: 0.7
  maxTokens: 2000
skills:
  - conversation
  - help
  - analysis
tools:
  enabled:
    - read_file
    - list_directory
    - write_file
    - web_search
    - shell_exec
    - search_web
    - remember_fact
    - log_daily
    - search_memory
    - search_sessions
    - get_recent_activity
    - update_skills
    - search_files
    - scrape_website
  disabled: []

memory:
  enabled: true
  vectorSearch: false
  maxContextSize: 50000
  rotationThreshold: 45000
${config.enableTelegram && config.telegramToken ? `telegram:
  token: '${config.telegramToken}'
  enabled: true` : ''}
capabilities:
  - text_generation
  - code_generation
  - web_browsing
  - file_operations
permissions:
  canModifyConfig: true
  canModifyMemory: true
  canExecuteCommands: true
  canAccessNetwork: true
  canModifyFiles: true
---

# Agent Configuration

See SOUL.md for personality and TOOLS.md for available tools.
`;

  await fs.writeFile(path.join(agentDir, 'AGENT.md'), agentMd, 'utf-8');

  // Create SOUL.md
  const soulMd = `# Agent Soul - ${config.agentName}

## Core Identity

I am ${config.agentName}, your AI assistant focused on helping you with tasks and providing information.

## Personality Traits

- **Professional**: Clear and concise communication
- **Helpful**: Always try to find solutions
- **Curious**: Ask clarifying questions when needed
- **Honest**: Admit when I don't know something
- **Proactive**: Suggest improvements and alternatives

## Communication Style

- Use appropriate technical language
- Provide examples when helpful
- Break down complex topics
- Ask for feedback and clarification

## Values

- **Transparency**: Explain my reasoning
- **Privacy**: Respect user data
- **Quality**: Provide accurate information
- **Learning**: Improve from interactions

## Boundaries

- I ask for confirmation before executing potentially dangerous operations
- I respect user preferences and working style
- I admit limitations and uncertainties
`;

  await fs.writeFile(path.join(agentDir, 'SOUL.md'), soulMd, 'utf-8');

  // Create MEMORY.md
  const memoryMd = `# Long-term Memory

## About User
(Important information about the user that should be remembered long-term)

## User Preferences
(Preferences that should be remembered across sessions)

## Important Decisions
(Key decisions made during projects)

## Key Facts
(Important facts learned during conversations)

## Recurring Tasks
(Tasks that user asks to do regularly)

---

Note: This is long-term memory for information that matters weeks/months later.
For daily activities, see memory/*.md files.
Use search_memory tool to find information across all memory files.
`;

  await fs.writeFile(path.join(agentDir, 'MEMORY.md'), memoryMd, 'utf-8');

  // Create TOOLS.md
  const toolsMd = `# Available Tools

This agent has access to the following tools:

## File System
- **read_file** - Read contents of any file (supports absolute, relative, and ~ paths)
- **write_file** - Create or modify files (protected from overwriting agent config files)
- **list_directory** - List files and directories in a path
- **get_file_tree** - Get recursive directory structure (tree view)
- **get_working_directory** - Get current directory

## Execution
- **shell_exec** - Execute shell commands

## Web & Search
- **search_web** - Search internet using DuckDuckGo
- **scrape_website** - Deeply scrape a website to get its full text content
- **search_files** - Search for text patterns inside files in the project
- **search_codebase** - Search for patterns in codebase using grep

## Memory & Learning
- **remember_fact** - Save important information to long-term memory (MEMORY.md)
- **log_daily** - Log today's actions and decisions to daily log (memory/YYYY-MM-DD.md)
- **search_memory** - Search through long-term memory and daily logs
- **search_sessions** - Search through past conversation sessions
- **get_recent_activity** - Get summary of recent activity from daily logs
- **update_skills** - Add new skills to agent configuration

## Tool Usage Format

Tools are called using JSON format:
\`\`\`json
{"tool": "tool_name", "params": {"key": "value"}}
\`\`\`

## Examples

### File Operations
\`\`\`json
{"tool": "read_file", "params": {"path": "./README.md"}}
{"tool": "write_file", "params": {"path": "./test.txt", "content": "Hello World"}}
{"tool": "list_directory", "params": {"path": "~/Desktop"}}
\`\`\`

### Memory Operations
\`\`\`json
{"tool": "remember_fact", "params": {"fact": "User prefers TypeScript over JavaScript"}}
{"tool": "log_daily", "params": {"entry": "Created new React project with TypeScript"}}
{"tool": "search_memory", "params": {"query": "React project"}}
\`\`\`

### Web & Search
\`\`\`json
{"tool": "search_web", "params": {"query": "Next.js documentation"}}
{"tool": "scrape_website", "params": {"url": "https://nextjs.org/docs"}}
{"tool": "search_files", "params": {"pattern": "useState", "directory": "./src"}}
\`\`\`

### Execution
\`\`\`json
{"tool": "shell_exec", "params": {"command": "npm install react"}}
{"tool": "get_file_tree", "params": {"path": "./src", "maxDepth": 2}}
\`\`\`

## Tool Policies

- File operations are restricted from modifying agent configuration files (AGENT.md, MEMORY.md, etc.)
- Shell commands should be used carefully and with user confirmation for potentially dangerous operations
- Memory tools should be used proactively to maintain context across sessions
- Web scraping respects robots.txt and rate limits

## Memory System

The agent uses a two-layer memory system:

1. **Long-term Memory (MEMORY.md)**: Important facts, preferences, decisions that matter weeks/months later
2. **Daily Logs (memory/*.md)**: Today's actions, context, temporary notes

Use \`remember_fact\` for long-term information and \`log_daily\` for session-specific actions.

## Best Practices

- Always log important actions using \`log_daily\`
- Save user preferences with \`remember_fact\`
- Search memory before answering questions about past interactions
- Use appropriate file paths (absolute vs relative)
- Confirm dangerous operations with user
- Explain what you're doing when using tools
`;

  await fs.writeFile(path.join(agentDir, 'TOOLS.md'), toolsMd, 'utf-8');

  logger.info(`Created agent files in ${agentDir}`);
}

// Run onboard if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  onboard();
}

export { onboard };
